apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshfarmjuba-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - freshfarmjuba.com
    secretName: freshfarmjuba-tls
  rules:
  - host: freshfarmjuba.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freshfarmjuba-service
            port:
              number: 80
